pub mod camera;
pub mod grid;
pub mod mesh;

use std::{
    marker::PhantomData,
    num::NonZero,
    ops::{
        Deref,
        DerefMut,
        Range,
    },
    sync::Arc,
};

use bitflags::bitflags;
use bytemuck::{
    Pod,
    Zeroable,
};
use nalgebra::Matrix4;
use palette::{
    LinSrgba,
    Srgb,
};

use crate::composer::{
    renderer::{
        camera::{
            CameraConfig,
            CameraData,
            CameraProjection,
            CameraResources,
            Viewport,
        },
        mesh::{
            Mesh,
            WindingOrder,
        },
    },
    scene::{
        Changed,
        Label,
        Scene,
        SharedShape,
        Transform,
        VisualColor,
    },
};

/// Tag for entities that should be rendered
#[derive(Copy, Clone, Debug, Default)]
pub struct Render;

#[derive(Clone, Copy, Debug)]
pub struct ClearColor {
    pub clear_color: Srgb,
}

impl From<Srgb> for ClearColor {
    fn from(value: Srgb) -> Self {
        Self { clear_color: value }
    }
}

impl From<Srgb<u8>> for ClearColor {
    fn from(value: Srgb<u8>) -> Self {
        Self::from(value.into_format::<f32>())
    }
}

impl Default for ClearColor {
    fn default() -> Self {
        Self {
            clear_color: palette::named::ALICEBLUE.into_format(),
        }
    }
}

#[derive(Clone, Debug)]
pub struct WgpuContext {
    pub adapter: wgpu::Adapter,
    pub device: wgpu::Device,
    pub queue: wgpu::Queue,
    pub renderer_config: RendererConfig,
}

#[derive(Clone, Copy, Debug)]
pub struct RendererConfig {
    pub target_texture_format: wgpu::TextureFormat,
    pub depth_texture_format: wgpu::TextureFormat,
    pub multisample_count: u32,
}

#[derive(derive_more::Debug)]
pub struct Renderer {
    wgpu_context: WgpuContext,

    camera_bind_group_layout: wgpu::BindGroupLayout,
    instance_bind_group_layout: wgpu::BindGroupLayout,
    mesh_bind_group_layout: wgpu::BindGroupLayout,

    clear_pipeline: Pipeline,
    solid_pipeline: Pipeline,
    wiremesh_pipeline: Pipeline,

    instance_buffer: InstanceBuffer<InstanceData>,
    instance_bind_group: wgpu::BindGroup,
    instance_data: Vec<InstanceData>,

    draw_commands: Arc<Vec<DrawCommand>>,

    #[debug(ignore)]
    command_buffer: hecs::CommandBuffer,
}

impl Renderer {
    /// The winding order used by the renderer (indicating the front face of a
    /// polygon).
    ///
    /// Apparently this is the default for left-handed coordinate systems (not
    /// sure why it matters). We use this either way, and will tell the
    /// vertex shader to fix the ordering for meshes that are wound opposite
    /// (the ones generated by parry clockwise apparently)
    pub const WINDING_ORDER: WindingOrder = WindingOrder::CounterClockwise;

    pub fn new(wgpu_context: WgpuContext) -> Self {
        let camera_bind_group_layout =
            wgpu_context
                .device
                .create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                    label: Some("camera_bind_group_layout"),
                    entries: &[wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    }],
                });

        let instance_bind_group_layout =
            wgpu_context
                .device
                .create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                    label: Some("instance_bind_group_layout"),
                    entries: &[wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: true },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    }],
                });

        let mesh_bind_group_layout =
            wgpu_context
                .device
                .create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                    label: Some("mesh_bind_group_layout"),
                    entries: &[
                        // index buffer
                        wgpu::BindGroupLayoutEntry {
                            binding: 0,
                            visibility: wgpu::ShaderStages::VERTEX,
                            ty: wgpu::BindingType::Buffer {
                                ty: wgpu::BufferBindingType::Storage { read_only: true },
                                has_dynamic_offset: false,
                                min_binding_size: None,
                            },
                            count: None,
                        },
                        // vertex buffer
                        wgpu::BindGroupLayoutEntry {
                            binding: 1,
                            visibility: wgpu::ShaderStages::VERTEX,
                            ty: wgpu::BindingType::Buffer {
                                ty: wgpu::BufferBindingType::Storage { read_only: true },
                                has_dynamic_offset: false,
                                min_binding_size: None,
                            },
                            count: None,
                        },
                    ],
                });

        let clear_pipeline = Pipeline::new(
            &wgpu_context,
            "render/clear",
            wgpu::include_wgsl!("shaders/clear.wgsl"),
            &[&camera_bind_group_layout],
            // we don't need to write depth for the clear pipeline. egui_wgpu clears the depth
            // buffer when it creates the render pass (to a value of 1.0)
            false,
            wgpu::CompareFunction::Always,
            wgpu::PolygonMode::Fill,
            None,
        );

        let render_bind_group_layouts = [
            &camera_bind_group_layout,
            &instance_bind_group_layout,
            &mesh_bind_group_layout,
        ];

        let solid_pipeline = Pipeline::new_objects(
            &wgpu_context,
            "render/object/solid",
            &render_bind_group_layouts,
            wgpu::CompareFunction::Less,
            wgpu::PolygonMode::Fill,
            Some("vs_main_solid"),
        );

        let wiremesh_pipeline = Pipeline::new_objects(
            &wgpu_context,
            "render/object/wireframe",
            &render_bind_group_layouts,
            wgpu::CompareFunction::LessEqual,
            wgpu::PolygonMode::Line,
            Some("vs_main_wireframe"),
        );

        let instance_buffer =
            InstanceBuffer::new(256, wgpu::BufferUsages::STORAGE, &wgpu_context.device);
        let instance_bind_group = create_instance_bind_group(
            &wgpu_context.device,
            &instance_bind_group_layout,
            instance_buffer.buffer(),
        );

        Self {
            wgpu_context,
            camera_bind_group_layout,
            instance_bind_group_layout,
            mesh_bind_group_layout,
            clear_pipeline,
            solid_pipeline,
            wiremesh_pipeline,
            instance_buffer,
            instance_bind_group,
            instance_data: vec![],
            draw_commands: Default::default(),
            command_buffer: hecs::CommandBuffer::new(),
        }
    }

    /// Prepares for the world to be rendered
    ///
    /// This must be called once a frame before any views render using it.
    ///
    /// This will update rendering-related information in the world (e.g. by
    /// creating meshes from shapes), update GPU buffers when the relevant
    /// world-state changed and prepare the draw calls for this frame.
    ///
    /// All draw calls are prepared here since they can be shared by multiple
    /// views that render the same scene. Internally they're put into a
    /// `Arc<Vec<_>>`, so they're cheap to clone (which is done in
    /// [`Self::prepare_frame`]).
    pub fn prepare_world(&mut self, scene: &mut Scene) {
        // generate meshes (for rendering) for objects that don't have them yet.
        for (entity, (shape, label)) in scene
            .entities
            .query_mut::<(&SharedShape, Option<&Label>)>()
            .with::<&Render>()
            .without::<&Mesh>()
        {
            if let Some(mesh) = Mesh::from_shape(
                &*shape.0,
                &self.wgpu_context.device,
                &self.mesh_bind_group_layout,
            ) {
                self.command_buffer.insert_one(entity, mesh);
            }
            else {
                tracing::warn!(
                    "Entity {entity:?} (label {label:?}) was marked for rendering, but a mesh could not be constructed."
                );
                self.command_buffer.remove::<(Render,)>(entity);
            }
        }

        // update cameras whose viewports changed
        for (entity, (camera_projection, viewport)) in scene
            .entities
            .query_mut::<(&mut CameraProjection, &Viewport)>()
            .with::<&Changed<Viewport>>()
        {
            camera_projection.set_viewport(viewport);
            self.command_buffer.remove_one::<Changed<Viewport>>(entity);
        }

        // create uniforms for cameras
        for (entity, (camera_projection, camera_transform, clear_color)) in scene
            .entities
            .query_mut::<(&CameraProjection, &Transform, Option<&ClearColor>)>()
            .without::<&CameraResources>()
        {
            tracing::debug!(
                ?entity,
                ?camera_projection,
                ?camera_transform,
                ?clear_color,
                "creating camera"
            );
            let camera_data = CameraData::new(camera_projection, camera_transform, clear_color);
            let camera_resources = CameraResources::new(
                &self.camera_bind_group_layout,
                &self.wgpu_context.device,
                &camera_data,
            );
            self.command_buffer.insert_one(entity, camera_resources);
        }

        // apply buffered commands to world
        self.command_buffer.run_on(&mut scene.entities);

        // update uniforms for cameras
        for (_, (camera_resources, camera_projection, camera_transform, clear_color)) in
            scene.entities.query_mut::<(
                &mut CameraResources,
                &CameraProjection,
                &Transform,
                Option<&ClearColor>,
            )>()
        {
            let camera_data = CameraData::new(camera_projection, camera_transform, clear_color);
            camera_resources.update(&self.wgpu_context.queue, &camera_data);
        }

        // next we prepare the draw commands.
        // this is done once in prepare, so multiple view widgets can then use the draw
        // commands to render their scenes from different cameras.
        // the draw commands are stored in an `Arc<Vec<_>>`, so they can be easily sent
        // via paint callbacks.

        // clear instance data buffer
        let num_instances_last_frame = self.instance_data.len();
        self.instance_data.clear();
        let mut first_instance = 0;

        // try to reuse the draw_commands buffer if possible
        if Arc::get_mut(&mut self.draw_commands).is_none() {
            self.draw_commands = Arc::new(Vec::with_capacity(num_instances_last_frame));
        }
        let draw_commands = Arc::get_mut(&mut self.draw_commands).unwrap();

        // prepare the actual draw commands
        for (_, (transform, mesh, color)) in scene
            .entities
            .query::<(&Transform, &Mesh, &VisualColor)>()
            .with::<&Render>()
            .iter()
        {
            // instance flags
            let mut flags = InstanceFlags::SHOW_SOLID | InstanceFlags::SHOW_WIREFRAME;
            if mesh.winding_order != Self::WINDING_ORDER {
                flags |= InstanceFlags::REVERSE_WINDING;
            }

            // write per-instance data into a buffer
            self.instance_data
                .push(InstanceData::new(transform, color, flags));

            // for now every draw call will only draw one instance, but we could do
            // instancing for real later.
            let instances = first_instance..(first_instance + 1);
            first_instance += 1;

            // prepare draw commands
            draw_commands.push(DrawCommand {
                instances,
                indices: mesh.indices.clone(),
                bind_group: mesh.bind_group.clone(),
            });
        }

        // send instance data to gpu
        self.instance_buffer.write(
            &self.instance_data,
            &self.wgpu_context.device,
            &self.wgpu_context.queue,
            |buffer| {
                self.instance_bind_group = create_instance_bind_group(
                    &self.wgpu_context.device,
                    &self.instance_bind_group_layout,
                    buffer,
                )
            },
        );
    }

    /// Prepares rendering a frame for a specific view.
    ///
    /// This just fetches camera information and the prepared draw commands
    /// (from [`Self::prepare_world`]) and returns them as a [`DrawFrame`].
    ///
    /// The [`DrawFrame`] can be cloned and passed via [`egui::PaintCallback`]
    /// to do the actual rendering with a [`wgpu::RenderPass`].
    ///
    /// Note that the actual draw commands are prepared in
    /// [`Self::prepare_world`], since they can be shared by multiple view
    /// widgets.
    pub fn prepare_frame(
        &mut self,
        scene: &Scene,
        camera_entity: Option<hecs::Entity>,
    ) -> Option<DrawFrame> {
        // get bind group and config for our camera
        let Some((camera_bind_group, camera_config, has_clear_color)) =
            camera_entity.and_then(|camera_entity| {
                scene
                    .entities
                    .query_one::<(
                        &CameraResources,
                        Option<&CameraConfig>,
                        hecs::Satisfies<&ClearColor>,
                    )>(camera_entity)
                    .ok()
                    .and_then(|mut query| {
                        query
                            .get()
                            .map(|(camera_resources, camera_config, has_clear_color)| {
                                (
                                    camera_resources.bind_group.clone(),
                                    camera_config.cloned().unwrap_or_default(),
                                    has_clear_color,
                                )
                            })
                    })
            })
        else {
            // if we don't have a camera we can't do anything. since we can't bind a camera
            // bind group, we can't even clear. we could have a fallback camera
            // bind group that is only used for clearing. or separate the clear color from
            // the camera.
            return None;
        };

        Some(DrawFrame {
            camera_bind_group,
            instance_bind_group: self.instance_bind_group.clone(),
            draw_commands: self.draw_commands.clone(),
            clear_pipeline: has_clear_color.then(|| self.clear_pipeline.pipeline.clone()),
            solid_pipeline: camera_config
                .show_solid
                .then(|| self.solid_pipeline.pipeline.clone()),
            wireframe_pipeline: camera_config
                .show_wireframe
                .then(|| self.wiremesh_pipeline.pipeline.clone()),
        })
    }
}

fn create_instance_bind_group(
    device: &wgpu::Device,
    instance_bind_group_layout: &wgpu::BindGroupLayout,
    buffer: &wgpu::Buffer,
) -> wgpu::BindGroup {
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("instance bind group"),
        layout: &instance_bind_group_layout,
        entries: &[wgpu::BindGroupEntry {
            binding: 0,
            resource: buffer.as_entire_binding(),
        }],
    })
}

#[derive(Debug)]
struct Pipeline {
    shader_module: wgpu::ShaderModule,
    pipeline_layout: wgpu::PipelineLayout,
    pipeline: wgpu::RenderPipeline,
}

impl Pipeline {
    pub fn new(
        wgpu_context: &WgpuContext,
        label: &str,
        shader_module_desc: wgpu::ShaderModuleDescriptor,
        bind_group_layouts: &[&wgpu::BindGroupLayout],
        depth_write_enabled: bool,
        depth_compare: wgpu::CompareFunction,
        polygon_mode: wgpu::PolygonMode,
        vertex_shader_entry_point: Option<&str>,
    ) -> Self {
        let shader_module = wgpu_context.device.create_shader_module(shader_module_desc);

        let pipeline_layout =
            wgpu_context
                .device
                .create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                    label: Some(label),
                    bind_group_layouts,
                    push_constant_ranges: &[],
                });

        let pipeline =
            wgpu_context
                .device
                .create_render_pipeline(&wgpu::RenderPipelineDescriptor {
                    label: Some(label),
                    layout: Some(&pipeline_layout),
                    vertex: wgpu::VertexState {
                        module: &shader_module,
                        entry_point: vertex_shader_entry_point,
                        compilation_options: Default::default(),
                        buffers: &[],
                    },
                    primitive: wgpu::PrimitiveState {
                        topology: wgpu::PrimitiveTopology::TriangleList,
                        strip_index_format: None,
                        front_face: Renderer::WINDING_ORDER.front_face(),
                        cull_mode: Some(wgpu::Face::Back),
                        unclipped_depth: false,
                        polygon_mode,
                        conservative: false,
                    },
                    depth_stencil: Some(wgpu::DepthStencilState {
                        format: wgpu::TextureFormat::Depth32Float,
                        depth_write_enabled,
                        depth_compare,
                        stencil: Default::default(),
                        bias: Default::default(),
                    }),
                    multisample: wgpu::MultisampleState {
                        count: wgpu_context.renderer_config.multisample_count,
                        mask: !0,
                        alpha_to_coverage_enabled: false,
                    },
                    fragment: Some(wgpu::FragmentState {
                        module: &shader_module,
                        entry_point: None,
                        compilation_options: Default::default(),
                        targets: &[Some(wgpu::ColorTargetState {
                            format: wgpu_context.renderer_config.target_texture_format,
                            blend: Some(wgpu::BlendState::ALPHA_BLENDING),
                            write_mask: wgpu::ColorWrites::ALL,
                        })],
                    }),
                    multiview: None,
                    cache: None,
                });

        Self {
            shader_module,
            pipeline_layout,
            pipeline,
        }
    }

    pub fn new_objects(
        wgpu_context: &WgpuContext,
        label: &str,
        bind_group_layouts: &[&wgpu::BindGroupLayout],
        depth_compare: wgpu::CompareFunction,
        polygon_mode: wgpu::PolygonMode,
        vertex_shader_entry_point: Option<&str>,
    ) -> Self {
        Self::new(
            wgpu_context,
            label,
            wgpu::include_wgsl!("shaders/solid.wgsl"),
            bind_group_layouts,
            true,
            depth_compare,
            polygon_mode,
            vertex_shader_entry_point,
        )
    }
}

#[derive(Clone, Copy, Debug, Pod, Zeroable)]
#[repr(C)]
struct InstanceData {
    transform: Matrix4<f32>,
    solid_color: LinSrgba,
    wireframe_color: LinSrgba,
    flags: InstanceFlags,
    _padding: [u32; 3],
}

impl InstanceData {
    pub fn new(transform: &Transform, color: &VisualColor, flags: InstanceFlags) -> Self {
        Self {
            transform: transform.transform.cast().to_homogeneous(),
            // shaders work with linear colors
            solid_color: color.solid_color.into_linear(),
            wireframe_color: color.wireframe_color.into_linear(),
            flags,
            _padding: [0; _],
        }
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, Pod, Zeroable)]
    #[repr(C)]
    struct InstanceFlags: u32 {
        const REVERSE_WINDING = 0b0001;
        const SHOW_SOLID = 0b0010;
        const SHOW_WIREFRAME = 0b0100;
    }
}

#[derive(Debug)]
struct DrawCommand {
    /// range in the instance buffer to use
    instances: Range<u32>,

    /// range in the index buffer to use (usually `0..num_indices`)
    indices: Range<u32>,

    /// the bind group containing the index and vertex buffer for the mesh.
    bind_group: wgpu::BindGroup,
}

#[derive(Debug)]
pub struct DrawFrame {
    camera_bind_group: wgpu::BindGroup,
    instance_bind_group: wgpu::BindGroup,
    draw_commands: Arc<Vec<DrawCommand>>,
    clear_pipeline: Option<wgpu::RenderPipeline>,
    solid_pipeline: Option<wgpu::RenderPipeline>,
    wireframe_pipeline: Option<wgpu::RenderPipeline>,
}

impl DrawFrame {
    pub fn render(&self, render_pass: &mut wgpu::RenderPass<'static>) {
        // set camera
        render_pass.set_bind_group(0, &self.camera_bind_group, &[]);

        // clear
        if let Some(clear_pipeline) = &self.clear_pipeline {
            render_pass.set_pipeline(clear_pipeline);
            render_pass.draw(0..3, 0..1);
        }

        // set instance buffer (this is shared between all draw calls)
        render_pass.set_bind_group(1, &self.instance_bind_group, &[]);

        // render all objects with the solid and/or wireframe pipeline
        if let Some(solid_pipeline) = &self.solid_pipeline {
            render_objects_with_pipeline(solid_pipeline, render_pass, &self.draw_commands);
        }
        if let Some(wireframe_pipeline) = &self.wireframe_pipeline {
            render_objects_with_pipeline(wireframe_pipeline, render_pass, &self.draw_commands);
        }
    }
}

/// Helper function to render objects with a given pipeline.
///
/// Obviously the pipeline must be compatible. This works
/// with solid or wireframe rendering
fn render_objects_with_pipeline(
    pipeline: &wgpu::RenderPipeline,
    render_pass: &mut wgpu::RenderPass<'static>,
    draw_commands: &[DrawCommand],
) {
    // set draw (solid) pipeline
    render_pass.set_pipeline(pipeline);

    // issue draw commands
    for draw_command in draw_commands {
        render_pass.set_bind_group(2, &draw_command.bind_group, &[]);
        render_pass.draw(draw_command.indices.clone(), draw_command.instances.clone());
    }
}

#[derive(Debug)]
pub struct InstanceBuffer<T> {
    buffer: wgpu::Buffer,
    capacity: usize,
    usage: wgpu::BufferUsages,
    _phantom: PhantomData<[T]>,
}

impl<T> InstanceBuffer<T> {
    pub fn new(initial_capacity: usize, usage: wgpu::BufferUsages, device: &wgpu::Device) -> Self {
        Self {
            buffer: allocate_instance_buffer::<T>(initial_capacity, usage, device),
            capacity: initial_capacity,
            usage,
            _phantom: PhantomData,
        }
    }

    pub fn resize(&mut self, new_capacity: usize, device: &wgpu::Device) {
        assert!(new_capacity != 0);
        self.buffer = allocate_instance_buffer::<T>(new_capacity, self.usage, device);
    }

    pub fn resize_if_necessary(
        &mut self,
        needed_capacity: usize,
        device: &wgpu::Device,
        on_resize: impl FnOnce(&wgpu::Buffer),
    ) {
        if needed_capacity > self.capacity {
            self.resize((2 * self.capacity).max(needed_capacity), device);
            on_resize(&self.buffer);
        }
    }

    pub fn capacity(&self) -> usize {
        self.capacity
    }

    pub fn buffer(&self) -> &wgpu::Buffer {
        &self.buffer
    }

    pub fn write_view(&mut self, queue: &wgpu::Queue) -> InstanceBufferWriteView<'_, T> {
        let size = NonZero::new(buffer_size::<T>(self.capacity)).unwrap();
        let view = queue.write_buffer_with(&self.buffer, 0, size).unwrap();
        InstanceBufferWriteView {
            view,
            _phantom: PhantomData,
        }
    }
}

impl<T: Pod> InstanceBuffer<T> {
    pub fn write(
        &mut self,
        data: &[T],
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        on_resize: impl FnOnce(&wgpu::Buffer),
    ) {
        self.resize_if_necessary(data.len(), device, on_resize);
        queue.write_buffer(&self.buffer, 0, bytemuck::cast_slice(data));
    }
}

pub struct InstanceBufferWriteView<'a, T> {
    view: wgpu::QueueWriteBufferView,
    _phantom: PhantomData<&'a [T]>,
}

impl<'a, T: Pod> Deref for InstanceBufferWriteView<'a, T> {
    type Target = [T];

    fn deref(&self) -> &Self::Target {
        bytemuck::cast_slice(&*self.view)
    }
}

impl<'a, T: Pod> DerefMut for InstanceBufferWriteView<'a, T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        bytemuck::cast_slice_mut(&mut *self.view)
    }
}

fn buffer_size<T>(num_elements: usize) -> u64 {
    // fixme: this needs alignment/rounding
    (std::mem::size_of::<T>() * num_elements) as u64
}

fn allocate_instance_buffer<T>(
    capacity: usize,
    usage: wgpu::BufferUsages,
    device: &wgpu::Device,
) -> wgpu::Buffer {
    let size = buffer_size::<T>(capacity);
    device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("instance buffer"),
        size,
        usage: usage | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    })
}
