pub mod camera;
pub mod draw_commands;
pub mod grid;
pub mod light;
pub mod mesh;

use std::{
    marker::PhantomData,
    num::NonZero,
    ops::{
        Deref,
        DerefMut,
    },
};

use bitflags::bitflags;
use bytemuck::{
    Pod,
    Zeroable,
};
use nalgebra::Matrix4;
use palette::{
    Srgb,
    Srgba,
};
use serde::{
    Deserialize,
    Serialize,
};

use crate::app::composer::{
    renderer::{
        camera::{
            CameraConfig,
            CameraData,
            CameraProjection,
            CameraResources,
            Viewport,
        },
        draw_commands::{
            DrawCommand,
            DrawCommandBuffer,
            DrawCommandOptions,
        },
        light::{
            CameraLightFilter,
            Material,
            MaterialData,
        },
        mesh::{
            Mesh,
            WindingOrder,
        },
    },
    scene::{
        Changed,
        Label,
        Scene,
        SharedShape,
        Transform,
    },
};

/// Tag for entities that should be rendered
#[derive(Copy, Clone, Debug, Default, Serialize, Deserialize)]
pub struct Render;

// todo: respect eguis theme. we might just pass this in from the view when
// rendering and remove this component.
#[derive(Clone, Copy, Debug, Default, Serialize, Deserialize)]
pub struct ClearColor {
    pub clear_color: Srgb,
}

impl From<Srgb> for ClearColor {
    fn from(value: Srgb) -> Self {
        Self { clear_color: value }
    }
}

impl From<Srgb<u8>> for ClearColor {
    fn from(value: Srgb<u8>) -> Self {
        Self::from(value.into_format::<f32>())
    }
}

#[derive(Clone, Debug)]
pub struct WgpuContext {
    pub adapter: wgpu::Adapter,
    pub device: wgpu::Device,
    pub queue: wgpu::Queue,
    pub renderer_config: RendererConfig,
}

#[derive(Clone, Copy, Debug)]
pub struct RendererConfig {
    pub target_texture_format: wgpu::TextureFormat,
    pub depth_texture_format: Option<wgpu::TextureFormat>,
    pub multisample_count: u32,
}

/// # Notes
///
/// We use a left-handed coordinate system both in the scene and in NDC:
///  - x: from left to right
///  - y: from bottom to top
///  - z: from outside to inside of screen
///
/// Each [`Renderer`] can only render one scene at once, but through multiple
/// cameras.
///
/// # TODO
///
/// Split per-scene render-state from reusable state. Only `instance_buffer`,
/// `instance_bind_group` and `draw_command_buffer` are specific to the scene.
/// Everything else can be shared between renderers for multiple scenes. So we
/// could separate these out, and e.g. put them into a resource into the scene.
/// Note that `instance_data` can be shared. It's just a scratch buffer that is
/// used during `prepare_world`. Same for `command_buffer`.
#[derive(derive_more::Debug)]
pub struct Renderer {
    wgpu_context: WgpuContext,

    camera_bind_group_layout: wgpu::BindGroupLayout,
    instance_bind_group_layout: wgpu::BindGroupLayout,
    mesh_bind_group_layout: wgpu::BindGroupLayout,

    clear_pipeline: Pipeline,
    solid_pipeline: Pipeline,
    wireframe_pipeline: Pipeline,
    outline_pipeline: Pipeline,

    /// Scratch buffer for instance data (in GPU format)
    instance_data: Vec<InstanceData>,

    /// The instance buffer.
    ///
    /// [`InstanceBuffer`] will take care of the reallocation if the buffer
    /// needs to grow.
    instance_buffer: InstanceBuffer<InstanceData>,

    /// The bind group. This needs to be replace when the instance buffer grows.
    ///
    /// This is purposefully not included in [`InstanceBuffer`], because we
    /// might want to put other stuff in this bind group as well (e.g. point
    /// lights).
    instance_bind_group: wgpu::BindGroup,

    /// This stores all draw commands that are generated during `prepare_world`.
    /// Its `finish` method returns the finalized draw command (aggregate) for a
    /// specific camera.
    draw_command_buffer: DrawCommandBuffer,

    /// Scratch buffer for ECS commands
    #[debug(ignore)]
    command_buffer: hecs::CommandBuffer,
}

impl Renderer {
    /// The winding order used by the renderer (indicating the front face of a
    /// polygon).
    ///
    /// Apparently this is the default for left-handed coordinate systems (not
    /// sure why it matters). We use this either way, and will tell the
    /// vertex shader to fix the ordering for meshes that are wound opposite
    /// (the ones generated by parry clockwise apparently)
    pub const WINDING_ORDER: WindingOrder = WindingOrder::CounterClockwise;

    pub const MESH_SHADER_MODULE: wgpu::ShaderModuleDescriptor<'static> =
        wgpu::include_wgsl!("shaders/mesh.wgsl");

    pub fn new(wgpu_context: &WgpuContext) -> Self {
        let camera_bind_group_layout =
            wgpu_context
                .device
                .create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                    label: Some("camera_bind_group_layout"),
                    entries: &[wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Uniform,
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    }],
                });

        let instance_bind_group_layout =
            wgpu_context
                .device
                .create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                    label: Some("instance_bind_group_layout"),
                    entries: &[wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::VERTEX_FRAGMENT,
                        ty: wgpu::BindingType::Buffer {
                            ty: wgpu::BufferBindingType::Storage { read_only: true },
                            has_dynamic_offset: false,
                            min_binding_size: None,
                        },
                        count: None,
                    }],
                });

        let mesh_bind_group_layout =
            wgpu_context
                .device
                .create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                    label: Some("mesh_bind_group_layout"),
                    entries: &[
                        // index buffer
                        wgpu::BindGroupLayoutEntry {
                            binding: 0,
                            visibility: wgpu::ShaderStages::VERTEX,
                            ty: wgpu::BindingType::Buffer {
                                ty: wgpu::BufferBindingType::Storage { read_only: true },
                                has_dynamic_offset: false,
                                min_binding_size: None,
                            },
                            count: None,
                        },
                        // vertex buffer
                        wgpu::BindGroupLayoutEntry {
                            binding: 1,
                            visibility: wgpu::ShaderStages::VERTEX,
                            ty: wgpu::BindingType::Buffer {
                                ty: wgpu::BufferBindingType::Storage { read_only: true },
                                has_dynamic_offset: false,
                                min_binding_size: None,
                            },
                            count: None,
                        },
                    ],
                });

        let clear_pipeline = Pipeline::new(
            wgpu_context,
            "render/clear",
            Self::MESH_SHADER_MODULE,
            &[&camera_bind_group_layout],
            DepthState {
                // egui clears the depth buffer with a value of 1.0 when starting the render pass.
                // but we could enable this to write to the depth buffer with the clear shader - if
                // we want to clear to another value.
                write_enable: false,
                // render regardless of depth state
                compare: wgpu::CompareFunction::Always,
                bias: Default::default(),
            },
            {
                // this should always zero the stencil state
                let stencil_face_state = wgpu::StencilFaceState {
                    compare: wgpu::CompareFunction::Always,
                    fail_op: wgpu::StencilOperation::Zero,
                    depth_fail_op: wgpu::StencilOperation::Zero,
                    pass_op: wgpu::StencilOperation::Zero,
                };
                wgpu::StencilState {
                    // same stencil face state for both faces
                    front: stencil_face_state,
                    back: stencil_face_state,
                    // ignore buffer state
                    read_mask: 0x00,
                    // clear bits
                    // I thought a value of 0x00 would do it here, but the `is_enabled` method would
                    // return false then.
                    write_mask: 0xff,
                }
            },
            wgpu::PolygonMode::Fill,
            Some("vs_main_clear"),
            Some("fs_main_single_color"),
            false,
        );

        let render_bind_group_layouts = [
            &camera_bind_group_layout,
            &instance_bind_group_layout,
            &mesh_bind_group_layout,
        ];

        let solid_pipeline = Pipeline::new_objects(
            wgpu_context,
            "render/object/solid",
            &render_bind_group_layouts,
            wgpu::CompareFunction::Less,
            Some(Stencil::OUTLINE),
            None,
            wgpu::PolygonMode::Fill,
            Some("vs_main_solid"),
            Some("fs_main_solid"),
        );

        let wireframe_pipeline = Pipeline::new_objects(
            wgpu_context,
            "render/object/wireframe",
            &render_bind_group_layouts,
            wgpu::CompareFunction::LessEqual,
            None,
            None,
            wgpu::PolygonMode::Line,
            Some("vs_main_wireframe"),
            Some("fs_main_single_color"),
        );

        let outline_pipeline = Pipeline::new_objects(
            wgpu_context,
            "render/object/outline",
            &render_bind_group_layouts,
            wgpu::CompareFunction::Always,
            None,
            // mask used, todo: don't hardcode values like this :D
            Some(Stencil::OUTLINE),
            wgpu::PolygonMode::Fill,
            Some("vs_main_outline"),
            Some("fs_main_single_color"),
        );

        let instance_buffer =
            InstanceBuffer::new(256, wgpu::BufferUsages::STORAGE, &wgpu_context.device);
        let instance_bind_group = create_instance_bind_group(
            &wgpu_context.device,
            &instance_bind_group_layout,
            instance_buffer.buffer(),
        );

        Self {
            wgpu_context: wgpu_context.clone(),
            camera_bind_group_layout,
            instance_bind_group_layout,
            mesh_bind_group_layout,
            clear_pipeline,
            solid_pipeline,
            wireframe_pipeline,
            outline_pipeline,
            instance_buffer,
            instance_bind_group,
            instance_data: vec![],
            draw_command_buffer: Default::default(),
            command_buffer: hecs::CommandBuffer::new(),
        }
    }

    /// Prepares for the world to be rendered
    ///
    /// This must be called once a frame before any views render using it.
    ///
    /// This will update rendering-related information in the world (e.g. by
    /// creating meshes from shapes), update GPU buffers when the relevant
    /// world-state changed and prepare the draw calls for this frame.
    ///
    /// All draw calls are prepared here since they can be shared by multiple
    /// views that render the same scene. Internally they're put into a
    /// `Arc<Vec<_>>`, so they're cheap to clone (which is done in
    /// [`Self::prepare_frame`]).
    pub fn prepare_world(&mut self, scene: &mut Scene) {
        // generate meshes (for rendering) for objects that don't have them yet.
        for (entity, (shape, label)) in scene
            .entities
            .query_mut::<(&SharedShape, Option<&Label>)>()
            .with::<&Render>()
            .without::<&Mesh>()
        {
            if let Some(mesh) = Mesh::from_shape(
                &*shape.0,
                &self.wgpu_context.device,
                &self.mesh_bind_group_layout,
            ) {
                self.command_buffer.insert_one(entity, mesh);
            }
            else {
                tracing::warn!(
                    "Entity {entity:?} (label {label:?}) was marked for rendering, but a mesh could not be constructed."
                );
                self.command_buffer.remove::<(Render,)>(entity);
            }
        }

        // update cameras whose viewports changed
        for (entity, (camera_projection, viewport)) in scene
            .entities
            .query_mut::<(&mut CameraProjection, &Viewport)>()
            .with::<&Changed<Viewport>>()
        {
            camera_projection.set_viewport(viewport);
            self.command_buffer.remove_one::<Changed<Viewport>>(entity);
        }

        // create uniforms for cameras
        for (entity, (camera_projection, camera_transform, clear_color, camera_light_filter)) in
            scene
                .entities
                .query_mut::<(
                    &CameraProjection,
                    &Transform,
                    Option<&ClearColor>,
                    Option<&CameraLightFilter>,
                )>()
                .without::<&CameraResources>()
        {
            tracing::debug!(
                ?entity,
                ?camera_projection,
                ?camera_transform,
                ?clear_color,
                "creating camera"
            );
            let camera_data = CameraData::new(
                camera_projection,
                camera_transform,
                clear_color,
                camera_light_filter,
            );
            let camera_resources = CameraResources::new(
                &self.camera_bind_group_layout,
                &self.wgpu_context.device,
                &camera_data,
            );
            self.command_buffer.insert_one(entity, camera_resources);
        }

        // apply buffered commands to world
        self.command_buffer.run_on(&mut scene.entities);

        // update uniforms for cameras
        for (
            _,
            (
                camera_resources,
                camera_projection,
                camera_transform,
                clear_color,
                camera_light_filter,
            ),
        ) in scene.entities.query_mut::<(
            &mut CameraResources,
            &CameraProjection,
            &Transform,
            Option<&ClearColor>,
            Option<&CameraLightFilter>,
        )>() {
            let camera_data = CameraData::new(
                camera_projection,
                camera_transform,
                clear_color,
                camera_light_filter,
            );
            camera_resources.update(&self.wgpu_context.queue, &camera_data);
        }

        // next we prepare the draw commands.
        // this is done once in prepare, so multiple view widgets can then use the draw
        // commands to render their scenes from different cameras.
        // the draw commands are stored in an `Arc<Vec<_>>`, so they can be easily sent
        // via paint callbacks.

        // clear instance data buffer
        self.instance_data.clear();
        let mut first_instance = 0;

        // prepare the actual draw commands
        let mut draw_command_builder = self.draw_command_buffer.builder();
        for (_, (transform, mesh, material, outline)) in scene
            .entities
            .query::<(&Transform, &Mesh, &Material, Option<&Outline>)>()
            .with::<&Render>()
            .iter()
        {
            // instance flags
            let mut flags = InstanceFlags::SHOW_SOLID | InstanceFlags::SHOW_WIREFRAME;
            if mesh.winding_order != Self::WINDING_ORDER {
                flags |= InstanceFlags::REVERSE_WINDING;
            }

            // write per-instance data into a buffer
            self.instance_data.push(InstanceData::new(
                transform,
                material,
                flags,
                mesh.base_vertex,
                outline,
            ));

            // for now every draw call will only draw one instance, but we could do
            // instancing for real later.
            let instances = first_instance..(first_instance + 1);
            first_instance += 1;

            // prepare draw commands
            draw_command_builder.draw_mesh(instances, mesh, outline.is_some());
        }

        // send instance data to gpu
        self.instance_buffer.write(
            &self.instance_data,
            &self.wgpu_context.device,
            &self.wgpu_context.queue,
            |buffer| {
                self.instance_bind_group = create_instance_bind_group(
                    &self.wgpu_context.device,
                    &self.instance_bind_group_layout,
                    buffer,
                )
            },
        );
        self.instance_data.clear();
    }

    /// Prepares rendering a frame for a specific view.
    ///
    /// This just fetches camera information and the prepared draw commands
    /// (from [`Self::prepare_world`]) and returns them as a [`DrawCommand`].
    ///
    /// The [`DrawCommand`] can be cloned and passed via [`egui::PaintCallback`]
    /// to do the actual rendering with a [`wgpu::RenderPass`].
    ///
    /// Note that the actual draw commands are prepared in
    /// [`Self::prepare_world`], since they can be shared by multiple view
    /// widgets.
    pub fn prepare_frame(
        &mut self,
        scene: &Scene,
        camera_entity: Option<hecs::Entity>,
    ) -> Option<DrawCommand> {
        // get bind group and config for our camera
        let Some((camera_bind_group, camera_config, has_clear_color)) =
            camera_entity.and_then(|camera_entity| {
                scene
                    .entities
                    .query_one::<(
                        &CameraResources,
                        Option<&CameraConfig>,
                        hecs::Satisfies<&ClearColor>,
                    )>(camera_entity)
                    .ok()
                    .and_then(|mut query| {
                        query
                            .get()
                            .map(|(camera_resources, camera_config, has_clear_color)| {
                                (
                                    camera_resources.bind_group.clone(),
                                    camera_config.cloned().unwrap_or_default(),
                                    has_clear_color,
                                )
                            })
                    })
            })
        else {
            // fixme: use a fallback camera buffer to call the clear shader only.

            // if we don't have a camera we can't do anything. since we can't bind a camera
            // bind group, we can't even clear. we could have a fallback camera
            // bind group that is only used for clearing. or separate the clear color from
            // the camera.
            return None;
        };

        Some(self.draw_command_buffer.finish(
            self,
            camera_bind_group,
            DrawCommandOptions {
                enable_clear: has_clear_color,
                enable_solid: camera_config.show_solid,
                enable_wireframe: camera_config.show_wireframe,
                enable_outline: camera_config.show_outline,
            },
        ))
    }
}

fn create_instance_bind_group(
    device: &wgpu::Device,
    instance_bind_group_layout: &wgpu::BindGroupLayout,
    buffer: &wgpu::Buffer,
) -> wgpu::BindGroup {
    device.create_bind_group(&wgpu::BindGroupDescriptor {
        label: Some("instance bind group"),
        layout: instance_bind_group_layout,
        entries: &[wgpu::BindGroupEntry {
            binding: 0,
            resource: buffer.as_entire_binding(),
        }],
    })
}

#[derive(Debug)]
struct Pipeline {
    shader_module: wgpu::ShaderModule,
    pipeline_layout: wgpu::PipelineLayout,
    pipeline: wgpu::RenderPipeline,
}

impl Pipeline {
    #[allow(clippy::too_many_arguments)]
    fn new(
        wgpu_context: &WgpuContext,
        label: &str,
        shader_module_desc: wgpu::ShaderModuleDescriptor,
        bind_group_layouts: &[&wgpu::BindGroupLayout],
        depth_state: DepthState,
        stencil_state: wgpu::StencilState,
        polygon_mode: wgpu::PolygonMode,
        vertex_shader_entry_point: Option<&str>,
        fragment_shader_entry_point: Option<&str>,
        cull_back_faces: bool,
    ) -> Self {
        let cull_mode = cull_back_faces.then_some(wgpu::Face::Back);

        // We need to flip the interpretation of the winding order here, because this
        // actually depends on the orientation of our Z axis.
        let front_face = Renderer::WINDING_ORDER.flipped().front_face();

        let shader_module = wgpu_context.device.create_shader_module(shader_module_desc);

        let pipeline_layout =
            wgpu_context
                .device
                .create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                    label: Some(label),
                    bind_group_layouts,
                    push_constant_ranges: &[],
                });

        let pipeline =
            wgpu_context
                .device
                .create_render_pipeline(&wgpu::RenderPipelineDescriptor {
                    label: Some(label),
                    layout: Some(&pipeline_layout),
                    vertex: wgpu::VertexState {
                        module: &shader_module,
                        entry_point: vertex_shader_entry_point,
                        compilation_options: Default::default(),
                        buffers: &[],
                    },
                    primitive: wgpu::PrimitiveState {
                        topology: wgpu::PrimitiveTopology::TriangleList,
                        strip_index_format: None,
                        front_face,
                        cull_mode,
                        unclipped_depth: false,
                        polygon_mode,
                        conservative: false,
                    },
                    depth_stencil: wgpu_context.renderer_config.depth_texture_format.map(
                        |depth_texture_format| {
                            wgpu::DepthStencilState {
                                format: depth_texture_format,
                                depth_write_enabled: depth_state.write_enable,
                                depth_compare: depth_state.compare,
                                stencil: stencil_state,
                                bias: depth_state.bias,
                            }
                        },
                    ),
                    multisample: wgpu::MultisampleState {
                        count: wgpu_context.renderer_config.multisample_count,
                        mask: !0,
                        alpha_to_coverage_enabled: false,
                    },
                    fragment: Some(wgpu::FragmentState {
                        module: &shader_module,
                        entry_point: fragment_shader_entry_point,
                        compilation_options: Default::default(),
                        targets: &[Some(wgpu::ColorTargetState {
                            format: wgpu_context.renderer_config.target_texture_format,
                            blend: Some(wgpu::BlendState::ALPHA_BLENDING),
                            write_mask: wgpu::ColorWrites::ALL,
                        })],
                    }),
                    multiview: None,
                    cache: None,
                });

        Self {
            shader_module,
            pipeline_layout,
            pipeline,
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn new_objects(
        wgpu_context: &WgpuContext,
        label: &str,
        bind_group_layouts: &[&wgpu::BindGroupLayout],
        depth_compare: wgpu::CompareFunction,
        write_to_stencil_buffer: Option<Stencil>,
        test_against_stencil_buffer: Option<Stencil>,
        polygon_mode: wgpu::PolygonMode,
        vertex_shader_entry_point: Option<&str>,
        fragment_shader_entry_point: Option<&str>,
    ) -> Self {
        // enable/disable back-face culling. the mesh shader will paint back-faces
        // bright pink, so we'll know if something is flipped.
        const CULL_BACK_FACES: bool = true;

        let mut stencil_state = wgpu::StencilState::default();
        if let Some(write_mask) = write_to_stencil_buffer {
            // write stencil reference to stencil buffer
            stencil_state.front.pass_op = wgpu::StencilOperation::Replace;

            // remove this and the selected object will shine through anything occluding
            // with the outline color. give it a try :)
            stencil_state.front.depth_fail_op = wgpu::StencilOperation::Replace;

            // for now we'll replace all bits of the stencil buffer with the reference
            stencil_state.write_mask = write_mask.into();
        }
        if let Some(read_mask) = test_against_stencil_buffer {
            // check masked stencil buffer against stencil reference.

            // e.g. for outline drawing, when drawing the outline, the stencil reference
            // will be 0, so if the bit in the stencil buffer is set the test will fail and
            // thus the outline will not draw over the object itself.
            stencil_state.front.compare = wgpu::CompareFunction::Equal;
            stencil_state.read_mask = read_mask.into();
        }

        Self::new(
            wgpu_context,
            label,
            Renderer::MESH_SHADER_MODULE,
            bind_group_layouts,
            DepthState {
                write_enable: true,
                compare: depth_compare,
                bias: Default::default(),
            },
            stencil_state,
            polygon_mode,
            vertex_shader_entry_point,
            fragment_shader_entry_point,
            CULL_BACK_FACES,
        )
    }
}

/// # TODO
///
/// Could merge [`MaterialData`] directly into it and arrange fields such the we
/// save some bytes.
#[derive(Clone, Copy, Debug, Pod, Zeroable)]
#[repr(C)]
struct InstanceData {
    transform: Matrix4<f32>,
    flags: InstanceFlags,
    base_vertex: u32,
    _padding: [u32; 2],
    material: MaterialData,
}

impl InstanceData {
    pub fn new(
        transform: &Transform,
        material: &Material,
        flags: InstanceFlags,
        base_vertex: u32,
        outline: Option<&Outline>,
    ) -> Self {
        Self {
            transform: transform.transform.to_homogeneous(),
            flags,
            base_vertex,
            _padding: [0; _],
            material: MaterialData::new(material, outline),
        }
    }
}

bitflags! {
    #[derive(Clone, Copy, Debug, Pod, Zeroable)]
    #[repr(C)]
    struct InstanceFlags: u32 {
        const REVERSE_WINDING = 0b0001;

        // todo: these are not used currently. since we only render one
        // instance at a time currently, we could just not emit a draw call
        // of one of these is disabled.
        // if we were to render multiple instances at a time, we can use this
        // flag in the vertex shader to skip anything that it shouldn't render.
        const SHOW_SOLID = 0b0010;
        const SHOW_WIREFRAME = 0b0100;
        const SHOW_OUTLINE = 0b1000;
    }
}

#[derive(Debug)]
pub struct InstanceBuffer<T> {
    buffer: wgpu::Buffer,
    capacity: usize,
    usage: wgpu::BufferUsages,
    _phantom: PhantomData<[T]>,
}

impl<T> InstanceBuffer<T> {
    pub fn new(initial_capacity: usize, usage: wgpu::BufferUsages, device: &wgpu::Device) -> Self {
        Self {
            buffer: allocate_instance_buffer::<T>(initial_capacity, usage, device),
            capacity: initial_capacity,
            usage,
            _phantom: PhantomData,
        }
    }

    pub fn resize(&mut self, new_capacity: usize, device: &wgpu::Device) {
        assert!(new_capacity != 0);
        self.buffer = allocate_instance_buffer::<T>(new_capacity, self.usage, device);
    }

    pub fn resize_if_necessary(
        &mut self,
        needed_capacity: usize,
        device: &wgpu::Device,
        on_resize: impl FnOnce(&wgpu::Buffer),
    ) {
        if needed_capacity > self.capacity {
            self.resize((2 * self.capacity).max(needed_capacity), device);
            on_resize(&self.buffer);
        }
    }

    pub fn capacity(&self) -> usize {
        self.capacity
    }

    pub fn buffer(&self) -> &wgpu::Buffer {
        &self.buffer
    }

    pub fn write_view(&mut self, queue: &wgpu::Queue) -> InstanceBufferWriteView<'_, T> {
        let size = NonZero::new(buffer_size::<T>(self.capacity)).unwrap();
        let view = queue.write_buffer_with(&self.buffer, 0, size).unwrap();
        InstanceBufferWriteView {
            view,
            _phantom: PhantomData,
        }
    }
}

impl<T: Pod> InstanceBuffer<T> {
    pub fn write(
        &mut self,
        data: &[T],
        device: &wgpu::Device,
        queue: &wgpu::Queue,
        on_resize: impl FnOnce(&wgpu::Buffer),
    ) {
        self.resize_if_necessary(data.len(), device, on_resize);
        queue.write_buffer(&self.buffer, 0, bytemuck::cast_slice(data));
    }
}

pub struct InstanceBufferWriteView<'a, T> {
    view: wgpu::QueueWriteBufferView,
    _phantom: PhantomData<&'a [T]>,
}

impl<'a, T: Pod> Deref for InstanceBufferWriteView<'a, T> {
    type Target = [T];

    fn deref(&self) -> &Self::Target {
        bytemuck::cast_slice(&self.view)
    }
}

impl<'a, T: Pod> DerefMut for InstanceBufferWriteView<'a, T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        bytemuck::cast_slice_mut(&mut self.view)
    }
}

fn buffer_size<T>(num_elements: usize) -> u64 {
    // fixme: this needs alignment/rounding
    (std::mem::size_of::<T>() * num_elements) as u64
}

fn allocate_instance_buffer<T>(
    capacity: usize,
    usage: wgpu::BufferUsages,
    device: &wgpu::Device,
) -> wgpu::Buffer {
    let size = buffer_size::<T>(capacity);
    device.create_buffer(&wgpu::BufferDescriptor {
        label: Some("instance buffer"),
        size,
        usage: usage | wgpu::BufferUsages::COPY_DST,
        mapped_at_creation: false,
    })
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize)]
pub struct Outline {
    #[serde(with = "crate::util::serde::palette")]
    pub color: Srgba,
    pub thickness: f32,
}

impl Default for Outline {
    fn default() -> Self {
        Self {
            color: Srgba::new(1.0, 1.0, 1.0, 0.75),
            thickness: 0.1,
        }
    }
}

#[derive(Clone, Copy, Debug)]
struct DepthState {
    pub write_enable: bool,
    pub compare: wgpu::CompareFunction,
    pub bias: wgpu::DepthBiasState,
}

bitflags! {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
    pub struct Stencil: u8 {
        const OUTLINE = 0b0000_0001;
    }
}

impl From<Stencil> for u32 {
    fn from(value: Stencil) -> Self {
        value.bits().into()
    }
}
